### ISSUE TITLE
Autoscroll stopping randomly and jerking back to first slide after a while

### ISSUE THREAD

**Issue by alienkarma** [Splidejs/splide-extension-auto-scroll#2]
### Checks

- [X] Not a duplicate.
- [X] Not a question, feature request, or anything other than a bug report directly related to Splide. Use Discussions for these topics: https://github.com/Splidejs/splide/discussions

### Version

0.3.3

### Description

The splide autoscroll would initialize properly but then freeze and either freeze completely (unless hovered upon) or jerk back to the starting slide (rewind option is set to false)

The console throws up this exact error when it happens
> Uncaught TypeError: e.Slides.update is not a function
>    at ln (splide-extension-auto-scroll.min.js:6)
>    at cn (splide-extension-auto-scroll.min.js:6)
>    at i (splide-extension-auto-scroll.min.js:6)

My html structure is as below:-
`<div id="franchise-gallery" class="splide">`
`  <div id="franchise-gallery-container" class="splide__track">`
`    <ul id="franchise-gallery-list" class="splide__list">`
`      <li class="franchise-gallery-slide splide__slide loaded"><img src="1.jpg"></li>`
`      <li class="franchise-gallery-slide splide__slide loaded"><img src="2.jpg"></li>`
`      <li class="franchise-gallery-slide splide__slide loaded"><img src="3.jpg"></li>`
`    </ul>`
`  </div>`
`</div>`

And my script code is as below:-
`var gallery = new Splide('#franchise-gallery',{`
`		type   : 'loop',`
`		drag: 'free',`
`		autoWidth: true,`
`		pagination: false,`
`		arrows: false,`
`		autoScroll: {`
`			speed: 0.5,`
`			rewind: false,`
`			autoStart: true,`
`			pauseOnHover: true`
`		}`
`	}).mount(window.splide.Extensions);`
`	const { Autoplay } = gallery.Components;`

\* Also tried v3.4 but the script wont even start:-
> splide-extension-auto-scroll.cjs.min.js:13 Uncaught ReferenceError: exports is not defined
>    at splide-extension-auto-scroll.cjs.min.js:13

### Steps to Reproduce

1. Initialize splide and autoscroll extension as mentioned.
2. Output showing scrolling till the start of 3rd slide and bug occurs.

### Expected Behaviour

Scrolling smoothly and wrapping around to the 1st slide again

**Comment by NaotoshiFujita** [comment]
> e.Slides.update is not a function

This log tells me that you are using an older Splide version. Try with the latest one: v3.6.9.


> splide-extension-auto-scroll.cjs.min.js:13 Uncaught ReferenceError: exports is not defined

Do not include cjs (common js) file in the browser. It's mainly for the nodejs environment.

**Comment by alienkarma** [comment]
Just changed the splide cdn to the new version and its working perfectly (and got the proper splide auto scroll extension as well)
Thank you so much.

Also awesome work on the extension! Cheers!

**Comment by NaotoshiFujita** [comment]
Cool ✨
