### ISSUE TITLE
auto scroll stop after it scroll one slide and keep stoped until hoverd on them this happeningin cdn version

### ISSUE THREAD

**Issue by RAHUL1115** [Splidejs/splide-extension-auto-scroll#3]
### Checks

- [X] Not a duplicate.
- [X] Not a question, feature request, or anything other than a bug report directly related to Splide. Use Discussions for these topics: https://github.com/Splidejs/splide/discussions

### Version

v0.3.7

### Description

stops after scrolling on slide and dose not restart after interaction like this https://splidejs.com/extensions/auto-scroll/

### Reproduction Link

https://codesandbox.io/s/splide-test-iy87td?file=/index.html

### Steps to Reproduce

1. open the link
2. open preview in new window
3. open developer tool
4. wait for a second
5. second issue is
6. open the link 
7. and scroll the splide component using mouse or touch it will not start automatically.

### Expected Behaviour

excepted behavior should be like this example https://splidejs.com/extensions/auto-scroll/
- splide scroll without stopping.
- splide should continue to scroll after interaction.

**Comment by NaotoshiFujita** [comment]
I didn't see any issue on your example. Maybe your are looking for `type: 'loop'`?
```js
new Splide( '.splide', {
  type: 'loop',
} );
```
