### ISSUE TITLE
Rewind: false doesn't work when the last slide is near the left edge

### ISSUE THREAD

**Issue by hyvyys** [Splidejs/splide-extension-auto-scroll#4]
### Checks

- [X] Not a duplicate.
- [X] Not a question, feature request, or anything other than a bug report directly related to Splide. Use Discussions for these topics: https://github.com/Splidejs/splide/discussions

### Version

3.6.12

### Description

With the following code:

```js
import Splide from '@splidejs/splide';
import { AutoScroll } from '@splidejs/splide-extension-auto-scroll';


export default function init () {
    const slider = new Splide('.splide', {
        type     : 'loop',
        focus    : 'center',
        autoWidth: true,
        pauseOnHover: false,
        pauseOnFocus: false,
        rewind: false,
        speed: 1100,
        easing: 'cubic-bezier(.14,.1,.5,.7)',
        easing: 'cubic-bezier(.53,.12,.36,.87)',
        drag: 'free',
        easingFunc: t => 1 - Math.pow(1 - t, 2),
        autoScroll: {
            pauseOnHover: false,
            pauseOnFocus: false,
            rewind: false,
            speed: 1,
        },
    })
    .mount({ AutoScroll });
}
```

I'm getting a "rewind" behavior when trying to click previous slide when the last slide is near the left edge, time after time.

### Steps to Reproduce

1. Click previous when the last slide is near the left edge — slider rewinds despite setting rewind: false in both options and autoScroll options
2. Click previous again — slider seems stuck in this behavior, which makes it look like it's stuck on the current slide 

### Expected Behaviour

No rewind behavior, ability to switch slides further and further left

**Comment by NaotoshiFujita** [comment]
Thanks for your report. I've fixed the bug in the latest version.
