### ISSUE TITLE
 Property 'AutoScroll' of type 'AutoScrollComponent | undefined' is not assignable to string index type 'BaseComponent'

### ISSUE THREAD

**Issue by davidpawar** [Splidejs/splide-extension-auto-scroll#5]
### Checks

- [X] Not a duplicate.
- [X] Not a question, feature request, or anything other than a bug report directly related to Splide. Use Discussions for these topics: https://github.com/Splidejs/splide/discussions

### Version

v0.4.2

### Description

According to the documentation, I have added the AutoScroll extension.

```
import { Splide } from '@splidejs/splide';
import { AutoScroll } from '@splidejs/splide-extension-auto-scroll';

new Splide( '.splide' ).mount( { AutoScroll } );
```
After importing AutoScroll the build fails:

> Property 'AutoScroll' of type 'AutoScrollComponent | undefined' is not assignable to 'string' index type 'BaseComponent'.

Is that happening only for me?

### Steps to Reproduce

1. Follow the documentation to use AutoScroll https://splidejs.com/extensions/auto-scroll/
2. Start the project :-)

### Expected Behaviour

No build error.

**Comment by davidpawar** [comment]
Changing the interface inside AutoScroll.ts to:

```
    interface Components {
        AutoScroll: AutoScrollComponent;
    }
```

worked for me. Not sure if that's a suitable solution here.

**Comment by NaotoshiFujita** [comment]
I've checked it but haven't seen any error:
https://codesandbox.io/s/5-jmwgm7?file=/src/index.ts
