### ISSUE TITLE
transform: rotate slow down autoscroll and eventually stop it

### ISSUE THREAD

**Issue by MikolajChybowski** [Splidejs/splide-extension-auto-scroll#6]
### Checks

- [X] Not a duplicate.
- [X] Not a question, feature request, or anything other than a bug report directly related to Splide. Use Discussions for these topics: https://github.com/Splidejs/splide/discussions

### Version

v4.0.2

### Description

Seems like whatever (body, wrapping div, div.splide) have CSS attribute `transform: rotate(Xdeg)` it slows down autoscroll and eventually stop it.

![CleanShot 2022-05-15 at 12 52 55](https://user-images.githubusercontent.com/15613946/168469227-137a793d-ac23-4c18-9e68-ad88c7f5116e.gif)

### Steps to Reproduce

1. Visit https://splidejs.com/extensions/auto-scroll/
2. Add CSS attribute `transform: rotate(5deg)` to slider or even body
...

### Expected Behaviour

Autoscroll would work normally.

**Comment by NaotoshiFujita** [comment]
This is the design limitation. Splide does not work inside an element with transform since it uses `bondingClientRect`.
