### ISSUE TITLE
If autoscroll speed is negative (to play from right to left), images disappear after a while

### ISSUE THREAD

**Issue by alensimunic** [Splidejs/splide-extension-auto-scroll#7]
### Checks

- [X] Not a duplicate.
- [X] Not a question, feature request, or anything other than a bug report directly related to Splide. Use Discussions for these topics: https://github.com/Splidejs/splide/discussions

### Version

v4.0.1

### Description

Below is the code I tried using to get the slider to scroll in different direction. It works for a while, but after all images are scrolled once, they just dissapear.

`var splide = new Splide("#splidelower", {
      type: "loop",
      focus: "center",
      rewind: true,
      arrows: false,
      pagination: false,
      drag: false,
      pauseOnHover: false,
      perPage: 5,
      autoScroll: {
        speed: -0.8,
        pauseOnHover: false,
      },
    });
    splide.mount(window.splide.Extensions);`

### Steps to Reproduce

1. Set speed to negative value
2. Watch slider repeat

### Expected Behaviour

Images should not be disappearing

**Comment by the-Tofiq** [comment]
@alensimunic did you solve the problem?

**Comment by alensimunic** [comment]
> @alensimunic did you solve the problem?

Unfortunately no, we weren't able to pinpoint why images are disappearing. It seems like a more experienced person that knows the source code should take a look into this...

**Comment by NaotoshiFujita** [comment]
In the old versions, the extension did not support negative values for the `speed` option.
From ^0.5.0, it does.
https://splidejs.com/extensions/auto-scroll/#speed
