### ISSUE TITLE
Negative value not working on "slide" type.

### ISSUE THREAD

**Issue by Rados51** [Splidejs/splide-extension-auto-scroll#8]
### Checks

- [X] Not a duplicate.
- [X] Not a question, feature request, or anything other than a bug report directly related to Splide. Use Discussions for these topics: https://github.com/Splidejs/splide/discussions

### Version

v0.5.2

### Description

Negative values (reverse scroll) will not work if SplideJS type is set to "slide". If we use positive value, it will work fine.
Also, if it is set to "loop", everything work as expected.

### Reproduction Link

https://codesandbox.io/s/643-forked-le7c7g?file=/src/index.js

### Steps to Reproduce

1. Open CodeSandbox link
2. Change type to "loop" or change autoScroll.speed to positive value

### Expected Behaviour

Auto Scroll should work from beginning. Now it only works, if we move slider to last image, then it will start to scroll (on negative values).

**Comment by NaotoshiFujita** [comment]
You are using old versions.

![image](https://user-images.githubusercontent.com/38066259/188560498-1fcb841a-bf5e-4022-91fb-3d562b736433.png)

**Comment by Rados51** [comment]
@NaotoshiFujita 

HI, I have updated CodeBox to the latest versions for both packages, the issue still persist.

**Comment by NaotoshiFujita** [comment]
Ah, if you want to start it from the end slide on load, you need to specify the `start` index, since the initial index is `0`. For example:
https://codesandbox.io/s/splide-autoscroll-bug-forked-3l397r?file=/src/index.js

**Comment by radosek** [comment]
@NaotoshiFujita I see. Is this then desired effect as with `loop` type, it does not need`start` index? Would it be then possible to add option to use `start: -1` as some sliders have dynamic slides length, so it would be easier to use `-1` as last index one? Thanks.

**Comment by NaotoshiFujita** [comment]
>Is this then desired effect as with loop type, it does not need `start` index?

I don't know. It depends on what you want to achieve.

>Would it be then possible to add option to use start: -1 as some sliders have dynamic slides length, so it would be easier to use -1 as last index one?

I don't think so, since negative indices are used for clones internally. But you can easily get the last index by `querySelectorAll`.
